"""Exact global periodic intersection certification for straight net edges.

Candidate edge images are generated by the query-agnostic extended-object broad
phase in :mod:`mdstats.analysis._periodic_spatial`.  Every surviving segment pair
is tested exactly over rational fractional coordinates.  Since the Cartesian cell
map is invertible, segment intersection is affine-invariant and the rational test
is authoritative.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from fractions import Fraction
import hashlib
import json
from numbers import Integral
from typing import Any, Mapping, Sequence, TypeAlias

from ._periodic_graph import LatticeShift, coerce_lattice_shift
from ._periodic_spatial import (
    PeriodicAabbSupport,
    PeriodicImageCandidate,
    PeriodicSpatialCandidateSet,
    PeriodicSpatialMethod,
    PeriodicSpatialResources,
    build_periodic_overlap_candidates,
)
from .framework_topology import FrameworkEdgeKey
from .periodic_net_embedding import (
    PeriodicNetEmbedding,
    ProjectedEdgeCurveModel,
)
from .periodic_net_view import PeriodicNetView
from .primitive_ring import LiftedVertexRef

RationalVector3: TypeAlias = tuple[Fraction, Fraction, Fraction]

CANONICAL_PERIODIC_EDGE_CERTIFICATE_SCHEMA = "mdstats.periodic-edge-intersection-certificate.v1"
PERIODIC_EDGE_CERTIFICATE_DIGEST_ALGORITHM = "sha256-canonical-json-v1"


class PeriodicEdgeIntersectionError(ValueError):
    """Base exception for periodic edge-intersection certification."""


class PeriodicEdgeIntersectionInputError(PeriodicEdgeIntersectionError):
    """Raised when sources or exact segment inputs are malformed."""


class PeriodicEdgeIntersectionSerializationError(PeriodicEdgeIntersectionError):
    """Raised when a persisted certificate fails source replay."""


class PeriodicEdgeIntersectionStatus(str, Enum):
    """Global certification state for the straight projected edge model."""

    CERTIFIED_INTERSECTION_FREE = "certified-intersection-free"
    FORBIDDEN_INTERSECTIONS_FOUND = "forbidden-intersections-found"


class PeriodicEdgeContactKind(str, Enum):
    """Scientific classification of one exact geometric segment contact."""

    ALLOWED_COMMON_VERTEX = "allowed-common-vertex"
    FORBIDDEN_PROPER_CROSSING = "forbidden-proper-crossing"
    FORBIDDEN_ENDPOINT_ON_INTERIOR = "forbidden-endpoint-on-interior"
    FORBIDDEN_DISTINCT_ENDPOINT_CONTACT = "forbidden-distinct-endpoint-contact"
    FORBIDDEN_COLLINEAR_OVERLAP = "forbidden-collinear-overlap"

    @property
    def is_allowed(self) -> bool:
        return self is PeriodicEdgeContactKind.ALLOWED_COMMON_VERTEX


def _canonical_json(payload: Mapping[str, Any]) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def _digest(payload: Mapping[str, Any]) -> str:
    return hashlib.sha256(_canonical_json(payload).encode("utf-8")).hexdigest()


def _fraction_payload(value: Fraction) -> list[int]:
    return [value.numerator, value.denominator]


def _fraction_from_payload(value: Sequence[Any]) -> Fraction:
    if len(value) != 2:
        raise PeriodicEdgeIntersectionSerializationError(
            "Serialized rational values require [numerator, denominator]."
        )
    return Fraction(int(value[0]), int(value[1]))


def _add(left: RationalVector3, right: RationalVector3) -> RationalVector3:
    return tuple(a + b for a, b in zip(left, right, strict=True))  # type: ignore[return-value]


def _subtract(left: RationalVector3, right: RationalVector3) -> RationalVector3:
    return tuple(a - b for a, b in zip(left, right, strict=True))  # type: ignore[return-value]


def _scale(value: RationalVector3, factor: Fraction) -> RationalVector3:
    return tuple(component * factor for component in value)  # type: ignore[return-value]


def _cross(left: RationalVector3, right: RationalVector3) -> RationalVector3:
    return (
        left[1] * right[2] - left[2] * right[1],
        left[2] * right[0] - left[0] * right[2],
        left[0] * right[1] - left[1] * right[0],
    )


def _dot(left: RationalVector3, right: RationalVector3) -> Fraction:
    return sum(a * b for a, b in zip(left, right, strict=True))


def _zero(value: RationalVector3) -> bool:
    return value == (Fraction(0), Fraction(0), Fraction(0))


def _shift_vector(shift: LatticeShift) -> RationalVector3:
    return tuple(Fraction(value) for value in shift)  # type: ignore[return-value]


@dataclass(frozen=True, slots=True)
class _ExactSegmentIntersection:
    is_collinear_overlap: bool
    left_interval: tuple[Fraction, Fraction]
    right_interval: tuple[Fraction, Fraction]
    point: RationalVector3 | None


def _segment_intersection(
    p: RationalVector3,
    p_end: RationalVector3,
    q: RationalVector3,
    q_end: RationalVector3,
) -> _ExactSegmentIntersection | None:
    r = _subtract(p_end, p)
    s = _subtract(q_end, q)
    if _zero(r) or _zero(s):
        raise PeriodicEdgeIntersectionInputError(
            "Exact segment predicates require nonzero segments."
        )
    q_minus_p = _subtract(q, p)
    cross_rs = _cross(r, s)
    if not _zero(cross_rs):
        if _dot(q_minus_p, cross_rs) != 0:
            return None
        denominator = _dot(cross_rs, cross_rs)
        t = _dot(_cross(q_minus_p, s), cross_rs) / denominator
        u = _dot(_cross(q_minus_p, r), cross_rs) / denominator
        if t < 0 or t > 1 or u < 0 or u > 1:
            return None
        point = _add(p, _scale(r, t))
        return _ExactSegmentIntersection(False, (t, t), (u, u), point)

    if not _zero(_cross(q_minus_p, r)):
        return None
    axis = next(index for index, value in enumerate(r) if value != 0)
    t0 = (q[axis] - p[axis]) / r[axis]
    t1 = (q_end[axis] - p[axis]) / r[axis]
    lower = max(Fraction(0), min(t0, t1))
    upper = min(Fraction(1), max(t0, t1))
    if lower > upper:
        return None
    point_lower = _add(p, _scale(r, lower))
    if lower == upper:
        q_axis = s[axis]
        u = (point_lower[axis] - q[axis]) / q_axis
        return _ExactSegmentIntersection(False, (lower, lower), (u, u), point_lower)
    point_upper = _add(p, _scale(r, upper))
    q_axis = s[axis]
    u0 = (point_lower[axis] - q[axis]) / q_axis
    u1 = (point_upper[axis] - q[axis]) / q_axis
    return _ExactSegmentIntersection(
        True,
        (lower, upper),
        (min(u0, u1), max(u0, u1)),
        None,
    )


def _edge_endpoints(
    embedding: PeriodicNetEmbedding,
    edge_key: FrameworkEdgeKey,
    anchor_shift: LatticeShift,
) -> tuple[RationalVector3, RationalVector3]:
    start = embedding.fractional_coordinate(edge_key.vertex_i, anchor_shift)
    end_shift = tuple(
        anchor_shift[axis] + edge_key.image_shift[axis] for axis in range(3)
    )
    end = embedding.fractional_coordinate(edge_key.vertex_j, end_shift)
    return start, end


def _lifted_endpoints(
    edge_key: FrameworkEdgeKey, anchor_shift: LatticeShift
) -> tuple[LiftedVertexRef, LiftedVertexRef]:
    return (
        LiftedVertexRef(edge_key.vertex_i, anchor_shift),
        LiftedVertexRef(
            edge_key.vertex_j,
            tuple(anchor_shift[axis] + edge_key.image_shift[axis] for axis in range(3)),
        ),
    )


def _at_endpoint(parameter: Fraction) -> bool:
    return parameter == 0 or parameter == 1


def _contact_kind(
    exact: _ExactSegmentIntersection,
    left_key: FrameworkEdgeKey,
    right_key: FrameworkEdgeKey,
    right_shift: LatticeShift,
) -> tuple[PeriodicEdgeContactKind, LiftedVertexRef | None]:
    if exact.is_collinear_overlap:
        return PeriodicEdgeContactKind.FORBIDDEN_COLLINEAR_OVERLAP, None
    left_t = exact.left_interval[0]
    right_t = exact.right_interval[0]
    left_endpoint = _at_endpoint(left_t)
    right_endpoint = _at_endpoint(right_t)
    if left_endpoint and right_endpoint:
        left_ref = _lifted_endpoints(left_key, (0, 0, 0))[0 if left_t == 0 else 1]
        right_ref = _lifted_endpoints(right_key, right_shift)[0 if right_t == 0 else 1]
        if left_ref == right_ref:
            return PeriodicEdgeContactKind.ALLOWED_COMMON_VERTEX, left_ref
        return PeriodicEdgeContactKind.FORBIDDEN_DISTINCT_ENDPOINT_CONTACT, None
    if left_endpoint or right_endpoint:
        return PeriodicEdgeContactKind.FORBIDDEN_ENDPOINT_ON_INTERIOR, None
    return PeriodicEdgeContactKind.FORBIDDEN_PROPER_CROSSING, None


@dataclass(frozen=True, slots=True)
class PeriodicEdgeIntersection:
    """One exact contact between two explicit periodic edge placements."""

    left_edge_key: FrameworkEdgeKey
    right_edge_key: FrameworkEdgeKey
    relative_image_shift: LatticeShift
    contact_kind: PeriodicEdgeContactKind
    left_parameter_interval: tuple[Fraction, Fraction]
    right_parameter_interval: tuple[Fraction, Fraction]
    point_fractional: RationalVector3 | None = None
    common_vertex: LiftedVertexRef | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.left_edge_key, FrameworkEdgeKey) or not isinstance(
            self.right_edge_key, FrameworkEdgeKey
        ):
            raise PeriodicEdgeIntersectionInputError(
                "Intersection edge identities must be FrameworkEdgeKey records."
            )
        try:
            shift = coerce_lattice_shift(
                self.relative_image_shift, name="relative_image_shift"
            )
            kind = PeriodicEdgeContactKind(self.contact_kind)
        except ValueError as exc:
            raise PeriodicEdgeIntersectionInputError(str(exc)) from exc
        left = tuple(Fraction(value) for value in self.left_parameter_interval)
        right = tuple(Fraction(value) for value in self.right_parameter_interval)
        if len(left) != 2 or len(right) != 2:
            raise PeriodicEdgeIntersectionInputError(
                "Intersection parameter intervals must have two endpoints."
            )
        if not (0 <= left[0] <= left[1] <= 1 and 0 <= right[0] <= right[1] <= 1):
            raise PeriodicEdgeIntersectionInputError(
                "Intersection parameters must lie in the closed unit interval."
            )
        point = None
        if self.point_fractional is not None:
            point = tuple(Fraction(value) for value in self.point_fractional)
            if len(point) != 3:
                raise PeriodicEdgeIntersectionInputError(
                    "Intersection point must have three components."
                )
        common = self.common_vertex
        if common is not None and not isinstance(common, LiftedVertexRef):
            raise PeriodicEdgeIntersectionInputError(
                "common_vertex must be a LiftedVertexRef when present."
            )
        if kind.is_allowed and common is None:
            raise PeriodicEdgeIntersectionInputError(
                "Allowed common-vertex contacts require the exact lifted vertex."
            )
        object.__setattr__(self, "relative_image_shift", shift)
        object.__setattr__(self, "contact_kind", kind)
        object.__setattr__(self, "left_parameter_interval", left)
        object.__setattr__(self, "right_parameter_interval", right)
        object.__setattr__(self, "point_fractional", point)

    @property
    def is_allowed(self) -> bool:
        return self.contact_kind.is_allowed

    def to_dict(self) -> dict[str, Any]:
        return {
            "left_edge_key": self.left_edge_key.to_dict(),
            "right_edge_key": self.right_edge_key.to_dict(),
            "relative_image_shift": list(self.relative_image_shift),
            "contact_kind": self.contact_kind.value,
            "left_parameter_interval": [
                _fraction_payload(value) for value in self.left_parameter_interval
            ],
            "right_parameter_interval": [
                _fraction_payload(value) for value in self.right_parameter_interval
            ],
            "point_fractional": None
            if self.point_fractional is None
            else [_fraction_payload(value) for value in self.point_fractional],
            "common_vertex": None
            if self.common_vertex is None
            else self.common_vertex.to_dict(),
        }

    @classmethod
    def from_dict(cls, payload: Mapping[str, Any]) -> "PeriodicEdgeIntersection":
        return cls(
            left_edge_key=FrameworkEdgeKey.from_dict(payload["left_edge_key"]),
            right_edge_key=FrameworkEdgeKey.from_dict(payload["right_edge_key"]),
            relative_image_shift=tuple(int(value) for value in payload["relative_image_shift"]),
            contact_kind=PeriodicEdgeContactKind(str(payload["contact_kind"])),
            left_parameter_interval=tuple(
                _fraction_from_payload(value)
                for value in payload["left_parameter_interval"]
            ),
            right_parameter_interval=tuple(
                _fraction_from_payload(value)
                for value in payload["right_parameter_interval"]
            ),
            point_fractional=None
            if payload.get("point_fractional") is None
            else tuple(
                _fraction_from_payload(value) for value in payload["point_fractional"]
            ),
            common_vertex=None
            if payload.get("common_vertex") is None
            else LiftedVertexRef.from_dict(payload["common_vertex"]),
        )


@dataclass(frozen=True, slots=True, eq=False)
class PeriodicEdgeIntersectionCertificate:
    """Source-bound exact global certificate for one straight-edge embedding."""

    periodic_net_view_digest: str
    topology_graph_digest: str
    periodic_net_embedding_digest: str
    spatial_candidate_set_digest: str
    broad_phase_method: PeriodicSpatialMethod
    edge_count: int
    translation_image_count: int
    candidate_count: int
    exact_test_count: int
    allowed_common_vertex_contact_count: int
    forbidden_intersections: tuple[PeriodicEdgeIntersection, ...]
    status: PeriodicEdgeIntersectionStatus
    canonical_schema_version: str = CANONICAL_PERIODIC_EDGE_CERTIFICATE_SCHEMA
    digest_algorithm: str = PERIODIC_EDGE_CERTIFICATE_DIGEST_ALGORITHM
    digest: str = ""

    def __post_init__(self) -> None:
        for name in (
            "periodic_net_view_digest",
            "topology_graph_digest",
            "periodic_net_embedding_digest",
            "spatial_candidate_set_digest",
        ):
            value = getattr(self, name)
            if not isinstance(value, str) or len(value) != 64:
                raise PeriodicEdgeIntersectionInputError(
                    f"{name} must be a SHA-256 digest."
                )
        method = PeriodicSpatialMethod(self.broad_phase_method)
        status = PeriodicEdgeIntersectionStatus(self.status)
        for name in (
            "edge_count",
            "translation_image_count",
            "candidate_count",
            "exact_test_count",
            "allowed_common_vertex_contact_count",
        ):
            value = getattr(self, name)
            if isinstance(value, bool) or not isinstance(value, Integral) or int(value) < 0:
                raise PeriodicEdgeIntersectionInputError(
                    f"{name} must be a nonnegative integer."
                )
            object.__setattr__(self, name, int(value))
        intersections = tuple(self.forbidden_intersections)
        if any(
            not isinstance(item, PeriodicEdgeIntersection) or item.is_allowed
            for item in intersections
        ):
            raise PeriodicEdgeIntersectionInputError(
                "forbidden_intersections must contain only forbidden exact contacts."
            )
        if status is PeriodicEdgeIntersectionStatus.CERTIFIED_INTERSECTION_FREE and intersections:
            raise PeriodicEdgeIntersectionInputError(
                "An intersection-free certificate cannot contain forbidden contacts."
            )
        if status is PeriodicEdgeIntersectionStatus.FORBIDDEN_INTERSECTIONS_FOUND and not intersections:
            raise PeriodicEdgeIntersectionInputError(
                "A failed certificate must contain at least one forbidden contact."
            )
        if self.canonical_schema_version != CANONICAL_PERIODIC_EDGE_CERTIFICATE_SCHEMA or self.digest_algorithm != PERIODIC_EDGE_CERTIFICATE_DIGEST_ALGORITHM:
            raise PeriodicEdgeIntersectionInputError(
                "Unsupported periodic edge-intersection certificate schema."
            )
        object.__setattr__(self, "broad_phase_method", method)
        object.__setattr__(self, "status", status)
        object.__setattr__(self, "forbidden_intersections", intersections)
        expected = _digest(self._payload(False))
        if self.digest and self.digest != expected:
            raise PeriodicEdgeIntersectionInputError(
                "Stored periodic edge-intersection digest is inconsistent."
            )
        object.__setattr__(self, "digest", self.digest or expected)

    def __eq__(self, other: object) -> bool:
        return isinstance(other, PeriodicEdgeIntersectionCertificate) and self.digest == other.digest

    @property
    def certified(self) -> bool:
        return self.status is PeriodicEdgeIntersectionStatus.CERTIFIED_INTERSECTION_FREE

    def _payload(self, include_digest: bool) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "canonical_schema_version": self.canonical_schema_version,
            "digest_algorithm": self.digest_algorithm,
            "periodic_net_view_digest": self.periodic_net_view_digest,
            "topology_graph_digest": self.topology_graph_digest,
            "periodic_net_embedding_digest": self.periodic_net_embedding_digest,
            "spatial_candidate_set_digest": self.spatial_candidate_set_digest,
            "broad_phase_method": self.broad_phase_method.value,
            "edge_count": self.edge_count,
            "translation_image_count": self.translation_image_count,
            "candidate_count": self.candidate_count,
            "exact_test_count": self.exact_test_count,
            "allowed_common_vertex_contact_count": self.allowed_common_vertex_contact_count,
            "forbidden_intersections": [
                item.to_dict() for item in self.forbidden_intersections
            ],
            "status": self.status.value,
        }
        if include_digest:
            payload["digest"] = self.digest
        return payload

    def to_dict(self) -> dict[str, Any]:
        return self._payload(True)

    @classmethod
    def from_dict(
        cls,
        payload: Mapping[str, Any],
        *,
        view: PeriodicNetView,
        embedding: PeriodicNetEmbedding,
        method: PeriodicSpatialMethod | None = None,
        resources: PeriodicSpatialResources | None = None,
    ) -> "PeriodicEdgeIntersectionCertificate":
        try:
            restored = cls(
                periodic_net_view_digest=str(payload["periodic_net_view_digest"]),
                topology_graph_digest=str(payload["topology_graph_digest"]),
                periodic_net_embedding_digest=str(payload["periodic_net_embedding_digest"]),
                spatial_candidate_set_digest=str(payload["spatial_candidate_set_digest"]),
                broad_phase_method=PeriodicSpatialMethod(str(payload["broad_phase_method"])),
                edge_count=int(payload["edge_count"]),
                translation_image_count=int(payload["translation_image_count"]),
                candidate_count=int(payload["candidate_count"]),
                exact_test_count=int(payload["exact_test_count"]),
                allowed_common_vertex_contact_count=int(
                    payload["allowed_common_vertex_contact_count"]
                ),
                forbidden_intersections=tuple(
                    PeriodicEdgeIntersection.from_dict(item)
                    for item in payload["forbidden_intersections"]
                ),
                status=PeriodicEdgeIntersectionStatus(str(payload["status"])),
                canonical_schema_version=str(payload["canonical_schema_version"]),
                digest_algorithm=str(payload["digest_algorithm"]),
                digest=str(payload["digest"]),
            )
            rebuilt = certify_periodic_straight_edge_embedding(
                view,
                embedding,
                method=restored.broad_phase_method if method is None else method,
                resources=resources,
            )
            if restored.to_dict() != rebuilt.to_dict():
                raise PeriodicEdgeIntersectionSerializationError(
                    "Serialized certificate is not canonical for the supplied sources."
                )
            return restored
        except PeriodicEdgeIntersectionError:
            raise
        except (KeyError, TypeError, ValueError) as exc:
            raise PeriodicEdgeIntersectionSerializationError(
                "Invalid periodic edge-intersection certificate payload."
            ) from exc


def _validate_sources(view: PeriodicNetView, embedding: PeriodicNetEmbedding) -> None:
    if not isinstance(view, PeriodicNetView):
        raise PeriodicEdgeIntersectionInputError("view must be a PeriodicNetView.")
    if not isinstance(embedding, PeriodicNetEmbedding):
        raise PeriodicEdgeIntersectionInputError(
            "embedding must be a PeriodicNetEmbedding."
        )
    if embedding.edge_curve_model is not ProjectedEdgeCurveModel.STRAIGHT_SEGMENT:
        raise PeriodicEdgeIntersectionInputError(
            "The first global certificate requires straight projected edges."
        )
    if (
        embedding.periodic_net_view_digest != view.digest
        or embedding.topology_graph_digest != view.source_graph_digest
        or embedding.vertex_atom_indices != view.vertex_atom_indices
        or embedding.edge_keys != view.edge_keys
    ):
        raise PeriodicEdgeIntersectionInputError(
            "PeriodicNetView and PeriodicNetEmbedding source identities differ."
        )


def _edge_supports(embedding: PeriodicNetEmbedding) -> tuple[PeriodicAabbSupport, ...]:
    supports: list[PeriodicAabbSupport] = []
    for position, edge_key in enumerate(embedding.edge_keys):
        start, end = _edge_endpoints(embedding, edge_key, (0, 0, 0))
        supports.append(PeriodicAabbSupport.from_points(position, (start, end)))
    return tuple(supports)


def _test_candidate(
    embedding: PeriodicNetEmbedding,
    candidate: PeriodicImageCandidate,
) -> PeriodicEdgeIntersection | None:
    left_key = embedding.edge_keys[candidate.object_i]
    right_key = embedding.edge_keys[candidate.object_j]
    left_start, left_end = _edge_endpoints(embedding, left_key, (0, 0, 0))
    right_start, right_end = _edge_endpoints(
        embedding, right_key, candidate.image_shift
    )
    exact = _segment_intersection(left_start, left_end, right_start, right_end)
    if exact is None:
        return None
    kind, common = _contact_kind(
        exact, left_key, right_key, candidate.image_shift
    )
    return PeriodicEdgeIntersection(
        left_edge_key=left_key,
        right_edge_key=right_key,
        relative_image_shift=candidate.image_shift,
        contact_kind=kind,
        left_parameter_interval=exact.left_interval,
        right_parameter_interval=exact.right_interval,
        point_fractional=exact.point,
        common_vertex=common,
    )


def certify_periodic_straight_edge_embedding(
    view: PeriodicNetView,
    embedding: PeriodicNetEmbedding,
    *,
    method: PeriodicSpatialMethod = PeriodicSpatialMethod.AUTO,
    resources: PeriodicSpatialResources | None = None,
) -> PeriodicEdgeIntersectionCertificate:
    """Certify all periodic straight-edge image contacts exactly."""

    _validate_sources(view, embedding)
    candidate_set: PeriodicSpatialCandidateSet = build_periodic_overlap_candidates(
        _edge_supports(embedding),
        source_digest=embedding.digest,
        method=method,
        resources=resources,
    )
    allowed = 0
    forbidden: list[PeriodicEdgeIntersection] = []
    for candidate in candidate_set.candidates:
        contact = _test_candidate(embedding, candidate)
        if contact is None:
            continue
        if contact.is_allowed:
            allowed += 1
        else:
            forbidden.append(contact)
    forbidden.sort(
        key=lambda item: (
            embedding.edge_position(item.left_edge_key),
            embedding.edge_position(item.right_edge_key),
            item.relative_image_shift,
            item.contact_kind.value,
        )
    )
    status = (
        PeriodicEdgeIntersectionStatus.FORBIDDEN_INTERSECTIONS_FOUND
        if forbidden
        else PeriodicEdgeIntersectionStatus.CERTIFIED_INTERSECTION_FREE
    )
    return PeriodicEdgeIntersectionCertificate(
        periodic_net_view_digest=view.digest,
        topology_graph_digest=view.source_graph_digest,
        periodic_net_embedding_digest=embedding.digest,
        spatial_candidate_set_digest=candidate_set.digest,
        broad_phase_method=candidate_set.method,
        edge_count=embedding.n_edges,
        translation_image_count=len(candidate_set.translation_stencil),
        candidate_count=len(candidate_set.candidates),
        exact_test_count=len(candidate_set.candidates),
        allowed_common_vertex_contact_count=allowed,
        forbidden_intersections=tuple(forbidden),
        status=status,
    )
