"""Choose the precision of MACE fine-tuning jobs generated by mdstats."""

from __future__ import annotations

from mdstats import MaceOptimizerPolicy


def optimizer_policy(*, use_float32: bool, device: str = "cuda") -> MaceOptimizerPolicy:
    """Return a protocol-bound optimizer policy for DATA8 job generation.

    The foundation MPA-0 checkpoint may remain float64. MACE converts the
    trainable model to this selected precision, and DATA9A execution evidence
    verifies the serialized final and target-head model state.
    """

    return MaceOptimizerPolicy(
        default_dtype="float32" if use_float32 else "float64",
        device=device,
    )


if __name__ == "__main__":
    print(optimizer_policy(use_float32=True))
