"""Finite periodic-net automorphism groups modulo lattice translations.

This module assembles the subgroup generated by explicitly supplied, already
validated :class:`~mdstats.analysis.ValidatedPeriodicAutomorphism` records.  Each
operation belongs to one immutable :class:`~mdstats.analysis.PeriodicNetView`.
Representatives are normalized by removing a common lattice translation at one
deterministic source anchor vertex.

The periodic quotient/vector representation follows Chung, Hahn, and Klee
(1984).  Exact combinatorial periodic-net automorphisms and finite
representatives modulo translations follow Delgado-Friedrichs and O'Keeffe
(2003).  mdstats adds deterministic source binding, explicit multiedge action,
and transactional finite closure. Primitive-ring actions remain in a separate, source-bound derived index.

This module does not discover generators automatically and does not compute a
Euclidean space group.

References
----------
S. J. Chung, Th. Hahn, and W. E. Klee, Acta Cryst. A 40, 42-50 (1984),
doi:10.1107/S0108767384000088.
O. Delgado-Friedrichs and M. O'Keeffe, Acta Cryst. A 59, 351-360 (2003),
doi:10.1107/S0108767303012017.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
import hashlib
import json
from numbers import Integral
from typing import Any, Mapping, Sequence

from ._periodic_graph import (
    add_shift,
    coerce_nonnegative_int,
    invert_unimodular_matrix3,
    matvec_shift,
    multiply_int_matrices3,
    negate_shift,
    subtract_shift,
)
from .framework_topology import FrameworkEdgeKey
from .periodic_net_view import PeriodicNetView
from .periodic_ring_action import (
    PeriodicEdgeImage,
    ValidatedPeriodicAutomorphism,
    build_validated_periodic_automorphism,
)
from .primitive_ring import LatticeShift, LiftedVertexRef


CANONICAL_PERIODIC_NET_SYMMETRY_SCHEMA = "mdstats.periodic_net_symmetry.v3"
PERIODIC_NET_SYMMETRY_DIGEST_ALGORITHM = "sha256-canonical-json-v1"


class NetSymmetryError(ValueError):
    """Base exception for finite periodic-net symmetry assembly."""


class NetSymmetryInputError(NetSymmetryError):
    """Raised when sources, generators, or limits are malformed."""


class NetSymmetryValidationError(NetSymmetryError):
    """Raised when exact group or induced-action invariants fail."""


class NetSymmetryResourceError(NetSymmetryError):
    """Raised when finite closure exceeds a declared resource limit."""


class NetSymmetrySerializationError(NetSymmetryError):
    """Raised when serialized symmetry data fail source or digest validation."""


def _positive_int(value: Any, *, name: str) -> int:
    if isinstance(value, bool) or not isinstance(value, Integral):
        raise NetSymmetryInputError(f"{name} must be an integer.")
    result = int(value)
    if result <= 0:
        raise NetSymmetryInputError(f"{name} must be positive.")
    return result


def _canonical_json(payload: Mapping[str, Any]) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def _digest(payload: Mapping[str, Any]) -> str:
    return hashlib.sha256(_canonical_json(payload).encode("utf-8")).hexdigest()


def _validate_view_action(
    view: PeriodicNetView,
    automorphism: ValidatedPeriodicAutomorphism,
) -> None:
    if not isinstance(view, PeriodicNetView):
        raise NetSymmetryInputError("view must be a PeriodicNetView.")
    if not isinstance(automorphism, ValidatedPeriodicAutomorphism):
        raise NetSymmetryInputError(
            "automorphism must be a ValidatedPeriodicAutomorphism."
        )
    if automorphism.periodic_net_view_digest != view.digest:
        raise NetSymmetryInputError(
            "Automorphism belongs to a different PeriodicNetView digest."
        )
    if automorphism.topology_graph_digest != view.source_graph_digest:
        raise NetSymmetryInputError(
            "Automorphism and PeriodicNetView have different topology graph digests."
        )
    if automorphism.vertex_atom_indices != view.vertex_atom_indices:
        raise NetSymmetryInputError(
            "Automorphism vertex domain is incompatible with the PeriodicNetView."
        )
    if len(automorphism.edge_images) != view.n_edges:
        raise NetSymmetryInputError(
            "Automorphism edge action is incompatible with the PeriodicNetView."
        )


def _anchor_atom(view: PeriodicNetView, anchor_atom_index: int | None) -> int:
    if not isinstance(view, PeriodicNetView):
        raise NetSymmetryInputError("view must be a PeriodicNetView.")
    if anchor_atom_index is None:
        return min(view.vertex_atom_indices)
    try:
        anchor = coerce_nonnegative_int(anchor_atom_index, name="anchor_atom_index")
    except ValueError as exc:
        raise NetSymmetryInputError(str(exc)) from exc
    if anchor not in view.vertex_atom_indices:
        raise NetSymmetryInputError(
            "anchor_atom_index must belong to the PeriodicNetView."
        )
    return anchor


def _operation_key(
    automorphism: ValidatedPeriodicAutomorphism,
) -> tuple[Any, ...]:
    return (
        automorphism.lattice_matrix,
        tuple(
            (image.atom_index, image.image_shift)
            for image in automorphism.vertex_images
        ),
        tuple(
            (image.target_edge_index, image.orientation)
            for image in automorphism.edge_images
        ),
    )


def normalize_periodic_automorphism(
    view: PeriodicNetView,
    automorphism: ValidatedPeriodicAutomorphism,
    *,
    anchor_atom_index: int | None = None,
) -> ValidatedPeriodicAutomorphism:
    """Remove the common output translation at one deterministic source anchor.

    Periodic-net representatives have the common-translation gauge freedom
    ``tau_i -> tau_i - c``.  Fixing ``tau_anchor = 0`` gives one exact
    representative modulo lattice translations; see Delgado-Friedrichs and
    O'Keeffe (2003).
    """

    _validate_view_action(view, automorphism)
    anchor = _anchor_atom(view, anchor_atom_index)
    common = automorphism.vertex_image(anchor).image_shift
    normalized_vertices = {
        source_atom: LiftedVertexRef(
            automorphism.vertex_image(source_atom).atom_index,
            subtract_shift(
                automorphism.vertex_image(source_atom).image_shift, common
            ),
        )
        for source_atom in view.vertex_atom_indices
    }
    return build_validated_periodic_automorphism(
        view,
        lattice_matrix=automorphism.lattice_matrix,
        vertex_images=normalized_vertices,
        edge_images=automorphism.edge_images,
    )


def identity_periodic_automorphism(
    view: PeriodicNetView,
    *,
    anchor_atom_index: int | None = None,
) -> ValidatedPeriodicAutomorphism:
    """Return the exact normalized identity operation for one net view."""

    _anchor_atom(view, anchor_atom_index)
    identity = build_validated_periodic_automorphism(
        view,
        lattice_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)),
        vertex_images={
            atom: LiftedVertexRef(atom, (0, 0, 0))
            for atom in view.vertex_atom_indices
        },
        edge_images=tuple(
            PeriodicEdgeImage(position, 1) for position in range(view.n_edges)
        ),
    )
    return normalize_periodic_automorphism(
        view, identity, anchor_atom_index=anchor_atom_index
    )


def compose_periodic_automorphisms(
    view: PeriodicNetView,
    outer: ValidatedPeriodicAutomorphism,
    inner: ValidatedPeriodicAutomorphism,
    *,
    anchor_atom_index: int | None = None,
) -> ValidatedPeriodicAutomorphism:
    """Return the normalized exact composition ``outer o inner``.

    For lifted representatives ``g`` and ``h``, composition uses
    ``A_g A_h`` and ``A_g tau_i^h + tau_{pi_h(i)}^g``.  Edge target positions
    compose as permutations and edge image orientations multiply.
    """

    _validate_view_action(view, outer)
    _validate_view_action(view, inner)
    anchor = _anchor_atom(view, anchor_atom_index)
    matrix = multiply_int_matrices3(
        outer.lattice_matrix, inner.lattice_matrix
    )
    vertex_images: dict[int, LiftedVertexRef] = {}
    for source_atom in view.vertex_atom_indices:
        inner_image = inner.vertex_image(source_atom)
        outer_image = outer.vertex_image(inner_image.atom_index)
        vertex_images[source_atom] = LiftedVertexRef(
            outer_image.atom_index,
            add_shift(
                matvec_shift(outer.lattice_matrix, inner_image.image_shift),
                outer_image.image_shift,
            ),
        )
    edge_images = tuple(
        PeriodicEdgeImage(
            outer.edge_images[inner_image.target_edge_index].target_edge_index,
            inner_image.orientation
            * outer.edge_images[inner_image.target_edge_index].orientation,
        )
        for inner_image in inner.edge_images
    )
    composed = build_validated_periodic_automorphism(
        view,
        lattice_matrix=matrix,
        vertex_images=vertex_images,
        edge_images=edge_images,
    )
    return normalize_periodic_automorphism(
        view, composed, anchor_atom_index=anchor
    )


def invert_periodic_automorphism(
    view: PeriodicNetView,
    automorphism: ValidatedPeriodicAutomorphism,
    *,
    anchor_atom_index: int | None = None,
) -> ValidatedPeriodicAutomorphism:
    """Return the normalized exact inverse of one validated operation."""

    _validate_view_action(view, automorphism)
    anchor = _anchor_atom(view, anchor_atom_index)
    inverse_matrix = invert_unimodular_matrix3(automorphism.lattice_matrix)
    vertex_images: dict[int, LiftedVertexRef] = {}
    for source_atom in view.vertex_atom_indices:
        image = automorphism.vertex_image(source_atom)
        vertex_images[image.atom_index] = LiftedVertexRef(
            source_atom,
            negate_shift(matvec_shift(inverse_matrix, image.image_shift)),
        )
    inverse_edges: list[PeriodicEdgeImage | None] = [None] * view.n_edges
    for source_position, image in enumerate(automorphism.edge_images):
        inverse_edges[image.target_edge_index] = PeriodicEdgeImage(
            source_position, image.orientation
        )
    if any(image is None for image in inverse_edges):  # pragma: no cover - constructor guard
        raise NetSymmetryValidationError("Edge action is not invertible.")
    inverse = build_validated_periodic_automorphism(
        view,
        lattice_matrix=inverse_matrix,
        vertex_images=vertex_images,
        edge_images=tuple(image for image in inverse_edges if image is not None),
    )
    return normalize_periodic_automorphism(
        view, inverse, anchor_atom_index=anchor
    )


def periodic_automorphism_composition_translation(
    view: PeriodicNetView,
    outer: ValidatedPeriodicAutomorphism,
    inner: ValidatedPeriodicAutomorphism,
    *,
    anchor_atom_index: int | None = None,
) -> LatticeShift:
    """Return the common translation removed from ``outer o inner``.

    Normalized representatives form a finite quotient only modulo pure lattice
    translations.  Their raw composition equals a common translation followed
    by the stored normalized product.  This exact translation cocycle is needed
    when the finite quotient acts on absolute lifted placements.
    """

    _validate_view_action(view, outer)
    _validate_view_action(view, inner)
    anchor = _anchor_atom(view, anchor_atom_index)
    inner_anchor = inner.vertex_image(anchor)
    outer_image = outer.vertex_image(inner_anchor.atom_index)
    return add_shift(
        matvec_shift(outer.lattice_matrix, inner_anchor.image_shift),
        outer_image.image_shift,
    )


def _automorphism_to_dict(
    automorphism: ValidatedPeriodicAutomorphism,
) -> dict[str, Any]:
    return {
        "lattice_matrix": [list(row) for row in automorphism.lattice_matrix],
        "vertex_images": [
            {
                "source_atom_index": source_atom,
                "target_atom_index": image.atom_index,
                "image_shift": list(image.image_shift),
            }
            for source_atom, image in zip(
                automorphism.vertex_atom_indices,
                automorphism.vertex_images,
                strict=True,
            )
        ],
        "edge_images": [
            {
                "target_edge_index": image.target_edge_index,
                "orientation": image.orientation,
            }
            for image in automorphism.edge_images
        ],
    }


def _automorphism_from_dict(
    payload: Mapping[str, Any], *, view: PeriodicNetView
) -> ValidatedPeriodicAutomorphism:
    try:
        return build_validated_periodic_automorphism(
            view,
            lattice_matrix=payload["lattice_matrix"],
            vertex_images={
                int(item["source_atom_index"]): LiftedVertexRef(
                    int(item["target_atom_index"]),
                    tuple(int(value) for value in item["image_shift"]),
                )
                for item in payload["vertex_images"]
            },
            edge_images=tuple(
                PeriodicEdgeImage(
                    int(item["target_edge_index"]),
                    int(item["orientation"]),  # type: ignore[arg-type]
                )
                for item in payload["edge_images"]
            ),
        )
    except (KeyError, TypeError, ValueError) as exc:
        if isinstance(exc, NetSymmetryError):
            raise
        raise NetSymmetrySerializationError(
            "Invalid serialized periodic automorphism payload."
        ) from exc


def _orbit_partition(
    elements: Sequence[Any], image_sets: Mapping[Any, set[Any]]
) -> tuple[tuple[Any, ...], ...]:
    remaining = set(elements)
    result: list[tuple[Any, ...]] = []
    while remaining:
        seed = min(remaining)
        orbit = tuple(sorted(image_sets[seed]))
        if not set(orbit).issubset(remaining):
            # Orbits of a valid group action partition the domain.  Reaching an
            # already consumed element signals inconsistent derived action data.
            raise NetSymmetryValidationError("Orbit sets do not form a partition.")
        remaining.difference_update(orbit)
        result.append(orbit)
    return tuple(result)


def _symmetry_payload(
    symmetry: "PeriodicNetSymmetry", *, include_digest: bool
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "canonical_schema_version": symmetry.canonical_schema_version,
        "digest_algorithm": symmetry.digest_algorithm,
        "periodic_net_view_digest": symmetry.periodic_net_view_digest,
        "topology_graph_digest": symmetry.topology_graph_digest,
        "anchor_atom_index": symmetry.anchor_atom_index,
        "operations": [
            _automorphism_to_dict(operation) for operation in symmetry.operations
        ],
        "multiplication_table": [
            list(row) for row in symmetry.multiplication_table
        ],
        "composition_translation_table": [
            [list(shift) for shift in row]
            for row in symmetry.composition_translation_table
        ],
        "inverse_operation_indices": list(symmetry.inverse_operation_indices),
        "identity_operation_index": symmetry.identity_operation_index,
        "vertex_orbits": [list(orbit) for orbit in symmetry.vertex_orbits],
        "edge_orbits": [
            [edge.to_dict() for edge in orbit] for orbit in symmetry.edge_orbits
        ],
    }
    if include_digest:
        payload["digest"] = symmetry.digest
    return payload


@dataclass(frozen=True, slots=True, eq=False)
class PeriodicNetSymmetry:
    """Finite exact subgroup of a PeriodicNetView automorphism group.

    The operation set is complete for the supplied generators, not necessarily
    for the full automorphism group of the view.
    """

    periodic_net_view_digest: str
    topology_graph_digest: str
    anchor_atom_index: int
    operations: tuple[ValidatedPeriodicAutomorphism, ...]
    multiplication_table: tuple[tuple[int, ...], ...]
    composition_translation_table: tuple[tuple[LatticeShift, ...], ...]
    inverse_operation_indices: tuple[int, ...]
    identity_operation_index: int
    vertex_orbits: tuple[tuple[int, ...], ...]
    edge_orbits: tuple[tuple[FrameworkEdgeKey, ...], ...]
    canonical_schema_version: str = CANONICAL_PERIODIC_NET_SYMMETRY_SCHEMA
    digest_algorithm: str = PERIODIC_NET_SYMMETRY_DIGEST_ALGORITHM
    digest: str = ""

    def __post_init__(self) -> None:
        if (
            not isinstance(self.periodic_net_view_digest, str)
            or len(self.periodic_net_view_digest) != 64
        ):
            raise NetSymmetryInputError(
                "periodic_net_view_digest must be a SHA-256 digest."
            )
        if (
            not isinstance(self.topology_graph_digest, str)
            or len(self.topology_graph_digest) != 64
        ):
            raise NetSymmetryInputError(
                "topology_graph_digest must be a SHA-256 digest."
            )
        try:
            anchor = coerce_nonnegative_int(
                self.anchor_atom_index, name="anchor_atom_index"
            )
        except ValueError as exc:
            raise NetSymmetryInputError(str(exc)) from exc
        operations = tuple(self.operations)
        if not operations:
            raise NetSymmetryInputError("operations must be nonempty.")
        for operation in operations:
            if not isinstance(operation, ValidatedPeriodicAutomorphism):
                raise NetSymmetryInputError(
                    "operations must contain ValidatedPeriodicAutomorphism records."
                )
            if (
                operation.periodic_net_view_digest
                != self.periodic_net_view_digest
                or operation.topology_graph_digest != self.topology_graph_digest
            ):
                raise NetSymmetryInputError(
                    "Every operation must share the symmetry source digests."
                )
            if operation.vertex_image(anchor).image_shift != (0, 0, 0):
                raise NetSymmetryInputError(
                    "Every operation must be normalized to the stored anchor."
                )
        n_operations = len(operations)
        table = tuple(tuple(int(value) for value in row) for row in self.multiplication_table)
        if len(table) != n_operations or any(len(row) != n_operations for row in table):
            raise NetSymmetryInputError(
                "multiplication_table must be square and aligned with operations."
            )
        if any(value < 0 or value >= n_operations for row in table for value in row):
            raise NetSymmetryInputError(
                "multiplication_table contains an invalid operation index."
            )
        translation_table = tuple(
            tuple(tuple(int(component) for component in shift) for shift in row)
            for row in self.composition_translation_table
        )
        if len(translation_table) != n_operations or any(
            len(row) != n_operations for row in translation_table
        ) or any(len(shift) != 3 for row in translation_table for shift in row):
            raise NetSymmetryInputError(
                "composition_translation_table must be an aligned square table of lattice shifts."
            )
        inverses = tuple(int(value) for value in self.inverse_operation_indices)
        if len(inverses) != n_operations or any(
            value < 0 or value >= n_operations for value in inverses
        ):
            raise NetSymmetryInputError(
                "inverse_operation_indices must align with operations."
            )
        identity = int(self.identity_operation_index)
        if identity < 0 or identity >= n_operations:
            raise NetSymmetryInputError("identity_operation_index is invalid.")
        for outer_index, outer in enumerate(operations):
            for inner_index, inner in enumerate(operations):
                inner_anchor = inner.vertex_image(anchor)
                outer_image = outer.vertex_image(inner_anchor.atom_index)
                expected_translation = add_shift(
                    matvec_shift(outer.lattice_matrix, inner_anchor.image_shift),
                    outer_image.image_shift,
                )
                if translation_table[outer_index][inner_index] != expected_translation:
                    raise NetSymmetryValidationError(
                        "composition_translation_table is inconsistent with the "
                        "normalized operation representatives."
                    )
        for index in range(n_operations):
            if table[identity][index] != index or table[index][identity] != index:
                raise NetSymmetryValidationError(
                    "multiplication_table does not contain a two-sided identity."
                )
            inverse = inverses[index]
            if table[index][inverse] != identity or table[inverse][index] != identity:
                raise NetSymmetryValidationError(
                    "inverse_operation_indices do not define two-sided inverses."
                )
        vertex_orbits = tuple(tuple(int(value) for value in orbit) for orbit in self.vertex_orbits)
        edge_orbits = tuple(tuple(orbit) for orbit in self.edge_orbits)
        if any(not orbit for orbit in vertex_orbits) or any(not orbit for orbit in edge_orbits):
            raise NetSymmetryInputError("Orbit records must be nonempty.")
        if any(tuple(sorted(set(orbit))) != orbit for orbit in vertex_orbits):
            raise NetSymmetryInputError("vertex_orbits must be sorted and unique.")
        if any(tuple(sorted(set(orbit))) != orbit for orbit in edge_orbits):
            raise NetSymmetryInputError("edge_orbits must be sorted and unique.")
        if self.canonical_schema_version != CANONICAL_PERIODIC_NET_SYMMETRY_SCHEMA:
            raise NetSymmetryInputError(
                "Unsupported periodic-net symmetry schema version."
            )
        if self.digest_algorithm != PERIODIC_NET_SYMMETRY_DIGEST_ALGORITHM:
            raise NetSymmetryInputError(
                "Unsupported periodic-net symmetry digest algorithm."
            )
        object.__setattr__(self, "anchor_atom_index", anchor)
        object.__setattr__(self, "operations", operations)
        object.__setattr__(self, "multiplication_table", table)
        object.__setattr__(self, "composition_translation_table", translation_table)
        object.__setattr__(self, "inverse_operation_indices", inverses)
        object.__setattr__(self, "identity_operation_index", identity)
        object.__setattr__(self, "vertex_orbits", vertex_orbits)
        object.__setattr__(self, "edge_orbits", edge_orbits)
        expected = _digest(_symmetry_payload(self, include_digest=False))
        digest = self.digest or expected
        if digest != expected:
            raise NetSymmetryInputError(
                "Stored periodic-net symmetry digest is inconsistent."
            )
        object.__setattr__(self, "digest", digest)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, PeriodicNetSymmetry):
            return NotImplemented
        return self.digest == other.digest and self.periodic_net_view_digest == other.periodic_net_view_digest

    @property
    def order(self) -> int:
        return len(self.operations)

    def compose_indices(self, outer_index: int, inner_index: int) -> int:
        try:
            outer = coerce_nonnegative_int(outer_index, name="outer_index")
            inner = coerce_nonnegative_int(inner_index, name="inner_index")
        except ValueError as exc:
            raise NetSymmetryInputError(str(exc)) from exc
        if outer >= self.order or inner >= self.order:
            raise NetSymmetryInputError("operation index is outside the group.")
        return self.multiplication_table[outer][inner]

    def composition_translation(
        self, outer_index: int, inner_index: int
    ) -> LatticeShift:
        """Return the common translation removed from one normalized product."""

        outer = self.compose_indices(outer_index, self.identity_operation_index)
        inner = self.compose_indices(inner_index, self.identity_operation_index)
        return self.composition_translation_table[outer][inner]

    def inverse_index(self, operation_index: int) -> int:
        try:
            index = coerce_nonnegative_int(operation_index, name="operation_index")
        except ValueError as exc:
            raise NetSymmetryInputError(str(exc)) from exc
        if index >= self.order:
            raise NetSymmetryInputError("operation index is outside the group.")
        return self.inverse_operation_indices[index]

    def to_dict(self) -> dict[str, Any]:
        return _symmetry_payload(self, include_digest=True)

    @classmethod
    def from_dict(
        cls,
        payload: Mapping[str, Any],
        *,
        view: PeriodicNetView,
    ) -> "PeriodicNetSymmetry":
        if not isinstance(view, PeriodicNetView):
            raise NetSymmetrySerializationError(
                "view must be a PeriodicNetView for source validation."
            )
        try:
            if payload["canonical_schema_version"] != CANONICAL_PERIODIC_NET_SYMMETRY_SCHEMA:
                raise NetSymmetrySerializationError(
                    "Unsupported serialized periodic-net symmetry schema."
                )
            if payload["periodic_net_view_digest"] != view.digest or payload[
                "topology_graph_digest"
            ] != view.source_graph_digest:
                raise NetSymmetrySerializationError(
                    "Serialized symmetry source digests do not match the supplied view."
                )
            operations = tuple(
                _automorphism_from_dict(item, view=view)
                for item in payload["operations"]
            )
            rebuilt = build_periodic_net_symmetry(
                view,
                operations,
                anchor_atom_index=int(payload["anchor_atom_index"]),
                max_operations=max(1, len(operations)),
            )
            if rebuilt.to_dict() != dict(payload):
                raise NetSymmetrySerializationError(
                    "Serialized periodic-net symmetry payload is not canonical."
                )
            return rebuilt
        except NetSymmetryError:
            raise
        except (KeyError, TypeError, ValueError) as exc:
            raise NetSymmetrySerializationError(
                "Invalid serialized PeriodicNetSymmetry payload."
            ) from exc


def build_periodic_net_symmetry(
    view: PeriodicNetView,
    generators: Sequence[ValidatedPeriodicAutomorphism],
    *,
    anchor_atom_index: int | None = None,
    max_operations: int = 512,
) -> PeriodicNetSymmetry:
    """Build the exact finite subgroup generated modulo lattice translations.

    Closure uses a Cayley-style breadth-first enumeration under normalized
    generators and their exact inverses.  The quotient/vector representation and
    representative normalization follow the periodic-net framework of Chung,
    Hahn & Klee (1984) and Delgado-Friedrichs & O'Keeffe (2003).

    The result is complete for the supplied generators only.  It is not a claim
    that automatic discovery has found the full automorphism group.
    """

    if not isinstance(view, PeriodicNetView):
        raise NetSymmetryInputError("view must be a PeriodicNetView.")
    anchor = _anchor_atom(view, anchor_atom_index)
    operation_limit = _positive_int(max_operations, name="max_operations")
    try:
        supplied = tuple(generators)
    except TypeError as exc:
        raise NetSymmetryInputError("generators must be an iterable.") from exc
    normalized_generators = tuple(
        normalize_periodic_automorphism(
            view, generator, anchor_atom_index=anchor
        )
        for generator in supplied
    )
    identity = identity_periodic_automorphism(
        view, anchor_atom_index=anchor
    )
    step_operations: dict[tuple[Any, ...], ValidatedPeriodicAutomorphism] = {}
    for operation in normalized_generators:
        step_operations[_operation_key(operation)] = operation
        inverse = invert_periodic_automorphism(
            view, operation, anchor_atom_index=anchor
        )
        step_operations[_operation_key(inverse)] = inverse
    steps = tuple(
        step_operations[key] for key in sorted(step_operations)
    )

    discovered: dict[tuple[Any, ...], ValidatedPeriodicAutomorphism] = {
        _operation_key(identity): identity
    }
    queue: deque[ValidatedPeriodicAutomorphism] = deque([identity])
    while queue:
        current = queue.popleft()
        for step in steps:
            candidate = compose_periodic_automorphisms(
                view,
                current,
                step,
                anchor_atom_index=anchor,
            )
            key = _operation_key(candidate)
            if key in discovered:
                continue
            if len(discovered) >= operation_limit:
                raise NetSymmetryResourceError(
                    "Generated symmetry closure exceeds max_operations; no partial "
                    "PeriodicNetSymmetry is returned."
                )
            discovered[key] = candidate
            queue.append(candidate)

    identity_key = _operation_key(identity)
    remaining_keys = sorted(key for key in discovered if key != identity_key)
    operations = (identity,) + tuple(discovered[key] for key in remaining_keys)
    operation_positions = {
        _operation_key(operation): position
        for position, operation in enumerate(operations)
    }
    table_rows: list[tuple[int, ...]] = []
    for outer in operations:
        row: list[int] = []
        for inner in operations:
            product = compose_periodic_automorphisms(
                view, outer, inner, anchor_atom_index=anchor
            )
            try:
                row.append(operation_positions[_operation_key(product)])
            except KeyError as exc:  # pragma: no cover - closure invariant
                raise NetSymmetryValidationError(
                    "Generated operation set is not closed under composition."
                ) from exc
        table_rows.append(tuple(row))
    multiplication_table = tuple(table_rows)
    composition_translation_table = tuple(
        tuple(
            periodic_automorphism_composition_translation(
                view, outer, inner, anchor_atom_index=anchor
            )
            for inner in operations
        )
        for outer in operations
    )
    identity_index = 0
    inverse_indices: list[int] = []
    for operation_index in range(len(operations)):
        candidates = [
            other_index
            for other_index in range(len(operations))
            if multiplication_table[operation_index][other_index] == identity_index
            and multiplication_table[other_index][operation_index] == identity_index
        ]
        if len(candidates) != 1:
            raise NetSymmetryValidationError(
                "An operation does not have exactly one two-sided inverse."
            )
        inverse_indices.append(candidates[0])

    vertex_image_sets = {
        atom: {
            operation.vertex_image(atom).atom_index for operation in operations
        }
        for atom in view.vertex_atom_indices
    }
    vertex_orbits = _orbit_partition(
        view.vertex_atom_indices, vertex_image_sets
    )
    edge_image_sets = {
        edge_key: {
            view.edge_keys[operation.edge_images[position].target_edge_index]
            for operation in operations
        }
        for position, edge_key in enumerate(view.edge_keys)
    }
    edge_orbits = _orbit_partition(view.edge_keys, edge_image_sets)



    return PeriodicNetSymmetry(
        periodic_net_view_digest=view.digest,
        topology_graph_digest=view.source_graph_digest,
        anchor_atom_index=anchor,
        operations=operations,
        multiplication_table=multiplication_table,
        composition_translation_table=composition_translation_table,
        inverse_operation_indices=tuple(inverse_indices),
        identity_operation_index=identity_index,
        vertex_orbits=vertex_orbits,
        edge_orbits=edge_orbits,
    )


__all__ = [
    "CANONICAL_PERIODIC_NET_SYMMETRY_SCHEMA",
    "PERIODIC_NET_SYMMETRY_DIGEST_ALGORITHM",
    "NetSymmetryError",
    "NetSymmetryInputError",
    "NetSymmetryResourceError",
    "NetSymmetrySerializationError",
    "NetSymmetryValidationError",
    "PeriodicNetSymmetry",
    "build_periodic_net_symmetry",
    "compose_periodic_automorphisms",
    "identity_periodic_automorphism",
    "invert_periodic_automorphism",
    "normalize_periodic_automorphism",
]
