"""Source-independent sampling and correlated-data partition primitives."""

from ._common import SamplingError, SamplingInputError, SamplingSerializationError
from .autocorrelation import (
    AUTOCORRELATION_ESTIMATE_SCHEMA,
    AUTOCORRELATION_POLICY_SCHEMA,
    AUTOCORRELATION_POLICY_VERSION,
    AutocorrelationEstimate,
    AutocorrelationEstimateStatus,
    AutocorrelationPolicy,
    effective_sample_count,
    estimate_autocorrelation,
    integrated_autocorrelation_time,
)
from .blocks import (
    COMPLETE_FRAME_BLOCK_PLAN_SCHEMA,
    COMPLETE_FRAME_BLOCK_POLICY_SCHEMA,
    COMPLETE_FRAME_BLOCK_POLICY_VERSION,
    FRAME_INTERVAL_SCHEMA,
    CompleteFrameBlockPlan,
    CompleteFrameBlockPolicy,
    FrameInterval,
    build_complete_frame_block_plan,
    contiguous_frame_runs,
    split_frame_interval,
)
from .assignment import (
    BALANCED_ASSIGNMENT_PLAN_SCHEMA,
    PURGED_FOLD_SCHEMA,
    PURGED_KFOLD_PLAN_SCHEMA,
    PURGED_KFOLD_POLICY_SCHEMA,
    PURGED_KFOLD_POLICY_VERSION,
    BalancedAssignmentPlan,
    PurgedFold,
    PurgedKFoldPlan,
    PurgedKFoldPolicy,
    assign_balanced_round_robin,
    build_purged_kfold_plan,
    purge_neighbor_positions,
)

__all__ = [
    "SamplingError",
    "SamplingInputError",
    "SamplingSerializationError",
    "AUTOCORRELATION_ESTIMATE_SCHEMA",
    "AUTOCORRELATION_POLICY_SCHEMA",
    "AUTOCORRELATION_POLICY_VERSION",
    "AutocorrelationEstimate",
    "AutocorrelationEstimateStatus",
    "AutocorrelationPolicy",
    "effective_sample_count",
    "estimate_autocorrelation",
    "integrated_autocorrelation_time",
    "COMPLETE_FRAME_BLOCK_PLAN_SCHEMA",
    "COMPLETE_FRAME_BLOCK_POLICY_SCHEMA",
    "COMPLETE_FRAME_BLOCK_POLICY_VERSION",
    "FRAME_INTERVAL_SCHEMA",
    "CompleteFrameBlockPlan",
    "CompleteFrameBlockPolicy",
    "FrameInterval",
    "build_complete_frame_block_plan",
    "contiguous_frame_runs",
    "split_frame_interval",
    "BALANCED_ASSIGNMENT_PLAN_SCHEMA",
    "PURGED_FOLD_SCHEMA",
    "PURGED_KFOLD_PLAN_SCHEMA",
    "PURGED_KFOLD_POLICY_SCHEMA",
    "PURGED_KFOLD_POLICY_VERSION",
    "BalancedAssignmentPlan",
    "PurgedFold",
    "PurgedKFoldPlan",
    "PurgedKFoldPolicy",
    "assign_balanced_round_robin",
    "build_purged_kfold_plan",
    "purge_neighbor_positions",
]
